// Base de itens da calculadora — Ragnarok Landverse America.
// `price` é o preço base de venda ao NPC (Sell) em pre-renewal.
// O Overcharge / Super Faturar Lv10 (+24%) é aplicado automaticamente no cálculo.
// Fonte: rAthena db/pre-re/item_db_etc.yml + CronusDATA PT-BR (CC BY-SA).
// Edite, adicione ou remova livremente.

window.ITEMS = [
  { id: 6379, pt: "7Star Board", en: "7Star Board", price: 10 },
  { id: 6265, pt: "Abacaxi", en: "Pineapple", price: 50 },
  { id: 6069, pt: "Abundance", en: "Abundance", price: 5 },
  { id: 6298, pt: "Abóbora Esmagada", en: "Pumpkin Head Crushed", price: 10 },
  { id: 11034, pt: "Acol Book Basic", en: "Acol Book Basic", price: 10 },
  { id: 11036, pt: "Acol Book Misc", en: "Acol Book Misc", price: 10 },
  { id: 11035, pt: "Acol Book Practice", en: "Acol Book Practice", price: 10 },
  { id: 7764, pt: "Adesivos Fortes", en: "High Strength Adhesive", price: 10 },
  { id: 7766, pt: "Alface", en: "Bok Choy", price: 10 },
  { id: 1098, pt: "Algemas", en: "Manacles", price: 329 },
  { id: 7345, pt: "Algemas", en: "Handcuffs", price: 362 },
  { id: 7213, pt: "Almofada de Alfinetes", en: "Needle Packet", price: 416 },
  { id: 704, pt: "Aloés", en: "Aloe", price: 250 },
  { id: 719, pt: "Ametista", en: "Amethyst", price: 3000 },
  { id: 6499, pt: "Ancient Grudge", en: "Ancient Grudge", price: 250 },
  { id: 7914, pt: "Ancient Language Document", en: "Ancient Language Document", price: 5 },
  { id: 7288, pt: "Anel de Compromisso", en: "Engagement Ring", price: 1 },
  { id: 7946, pt: "Anel de Ouro do Dia dos Namorados", en: "Gold Ring Of Valentine", price: 5 },
  { id: 7947, pt: "Anel de Prata do Dia dos Namorados", en: "Silver Ring Of Valentine", price: 5 },
  { id: 6395, pt: "Angel Magic Power", en: "Angel Magic Power", price: 410 },
  { id: 7163, pt: "Antenas Afiadas", en: "Hard Feeler", price: 285 },
  { id: 928, pt: "Antenas de Inseto", en: "Insect Feeler", price: 57 },
  { id: 6322, pt: "Antler Helmet", en: "Antler Helmet", price: 400 },
  { id: 973, pt: "Antígeno", en: "Counteragent", price: 400 },
  { id: 720, pt: "Aquamarina", en: "Aquamarine", price: 3000 },
  { id: 11031, pt: "Archer Book Basic", en: "Archer Book Basic", price: 10 },
  { id: 11033, pt: "Archer Book Misc", en: "Archer Book Misc", price: 10 },
  { id: 11032, pt: "Archer Book Practice", en: "Archer Book Practice", price: 10 },
  { id: 1061, pt: "Areia Estelar de Bruxa", en: "Witched Starsand", price: 242 },
  { id: 7043, pt: "Areia Fina", en: "Fine Sand", price: 50 },
  { id: 7124, pt: "Areia Molhada", en: "Sand Clump", price: 353 },
  { id: 7264, pt: "Areia Seca", en: "Dry Sand", price: 161 },
  { id: 941, pt: "Argola", en: "Nose Ring", price: 284 },
  { id: 1065, pt: "Armadilha", en: "Trap", price: 50 },
  { id: 7940, pt: "Armadilha Especial", en: "Special Alloy Trap", price: 100 },
  { id: 701, pt: "Armadilha para Insetos", en: "Ora Ora", price: 27500 },
  { id: 7210, pt: "Armadura de Dullahan", en: "Armor Piece of Dullahan", price: 395 },
  { id: 7069, pt: "Armadura Destruída", en: "Destroyed Armor", price: 521 },
  { id: 7344, pt: "Arquivo do Caso Shinokas", en: "Shinokas Case File", price: 10 },
  { id: 7006, pt: "Asa de Morcego Vermelho", en: "Wing of Red Bat", price: 84 },
  { id: 7104, pt: "Asas de Anjo Fajutas", en: "False Angel Wing", price: 378 },
  { id: 7064, pt: "Asas de Libélula", en: "Wing of Dragonfly", price: 260 },
  { id: 1058, pt: "Asas de Traça", en: "Moth Wings", price: 100 },
  { id: 7105, pt: "Auréola Fajuta", en: "False Heaven Ring", price: 462 },
  { id: 7223, pt: "Auto Retrato", en: "Contorted Self-Portrait", price: 1016 },
  { id: 7349, pt: "Autorização para o Arquivo", en: "Archive Permit", price: 10 },
  { id: 7796, pt: "Autógrafo do Autor", en: "Author's Autograph", price: 1 },
  { id: 1026, pt: "Avelã", en: "Acorn", price: 49 },
  { id: 7047, pt: "Avental de Alice", en: "Alice's Apron", price: 1212 },
  { id: 999, pt: "Aço", en: "Steel", price: 500 },
  { id: 7169, pt: "Ba Gua", en: "Ba Gua", price: 1400 },
  { id: 7269, pt: "Babador", en: "Pinafore", price: 480 },
  { id: 7119, pt: "Bactérias", en: "Bacillus", price: 512 },
  { id: 930, pt: "Bandagem Estragada", en: "Rotten Bandage", price: 175 },
  { id: 7549, pt: "Bandeira Nacional", en: "Brazilian Flag", price: 10 },
  { id: 7928, pt: "Bandeira Nacional", en: "Brazil National Flag", price: 5 },
  { id: 11055, pt: "Basic Adventure", en: "Basic Adventure", price: 10 },
  { id: 6386, pt: "Bath Water Sample", en: "Bath Water Sample", price: 10 },
  { id: 739, pt: "Batom", en: "Rouge", price: 5000 },
  { id: 925, pt: "Bico de Ave", en: "Bill of Birds", price: 32 },
  { id: 1040, pt: "Bigode de Anão Ancião", en: "Elder Pixie's Moustache", price: 116 },
  { id: 1017, pt: "Bigodes de Toupeira", en: "Mole Whiskers", price: 53 },
  { id: 986, pt: "Bigorna", en: "Anvil", price: 15000 },
  { id: 989, pt: "Bigorna de Emperium", en: "Emperium Anvil", price: 300000 },
  { id: 987, pt: "Bigorna de Oridecon", en: "Oridecon Anvil", price: 60000 },
  { id: 988, pt: "Bigorna de Ouro", en: "Golden Anvil", price: 150000 },
  { id: 7448, pt: "Bijuteria Amarela", en: "Yellow Bijou", price: 443 },
  { id: 7446, pt: "Bijuteria Azul", en: "Blue Bijou", price: 443 },
  { id: 7445, pt: "Bijuteria Verde", en: "Green Bijou", price: 443 },
  { id: 7447, pt: "Bijuteria Vermelha", en: "Red Bijou", price: 443 },
  { id: 7797, pt: "Bilhete do Autor", en: "Author's Memo", price: 1 },
  { id: 7297, pt: "Biotita", en: "Biotite", price: 1500 },
  { id: 7710, pt: "Black Gemstone", en: "Black Gemstone", price: 300 },
  { id: 7580, pt: "Black Marble", en: "Black Marble", price: 10 },
  { id: 6187, pt: "Blank Card", en: "Blank Card", price: 10 },
  { id: 6347, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6348, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6349, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6350, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6351, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6352, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6353, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6354, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6355, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 6356, pt: "Bless Word Paper", en: "Bless Word Paper", price: 2010 },
  { id: 7755, pt: "Bloco de Pesquisa", en: "Research Note", price: 10 },
  { id: 6061, pt: "Blood Beginner", en: "Blood Beginner", price: 50 },
  { id: 7907, pt: "Bobbin Of Goddess", en: "Bobbin Of Goddess", price: 10 },
  { id: 7547, pt: "Bola de Futebol", en: "Soccer Ball", price: 10 },
  { id: 746, pt: "Bolinha de Gude", en: "Glass Bead", price: 700 },
  { id: 6115, pt: "Bolinho Quente", en: "Bun", price: 500 },
  { id: 7767, pt: "Bolo para Bichinho", en: "Green Maiden's Cake", price: 10 },
  { id: 7212, pt: "Boneca Enforcada", en: "Hung Doll", price: 510 },
  { id: 750, pt: "Boneco de Bafomé", en: "Baphomet Doll", price: 9000 },
  { id: 7272, pt: "Boneco de Bolinho de Arroz", en: "Rice Ball Doll", price: 250 },
  { id: 742, pt: "Boneco de Chonchon", en: "Chonchon Doll", price: 1500 },
  { id: 743, pt: "Boneco de Esporo", en: "Spore Doll", price: 2750 },
  { id: 754, pt: "Boneco de Fumacento", en: "Raccoon Doll", price: 2500 },
  { id: 7206, pt: "Boneco de Gato Preto", en: "Black Cat Doll", price: 720 },
  { id: 7277, pt: "Boneco de Munak", en: "Munak Doll", price: 4450 },
  { id: 751, pt: "Boneco de Osíris", en: "Osiris Doll", price: 7000 },
  { id: 740, pt: "Boneco de Pelúcia", en: "Puppet", price: 500 },
  { id: 741, pt: "Boneco de Poring", en: "Poring Doll", price: 900 },
  { id: 752, pt: "Boneco de Rocker", en: "Rocker Doll", price: 2000 },
  { id: 753, pt: "Boneco de Yoyo", en: "Yoyo Doll", price: 3000 },
  { id: 6224, pt: "Bradium", en: "Bradium", price: 1000 },
  { id: 6090, pt: "Bradium Purificado", en: "Refined Bradium", price: 550 },
  { id: 1012, pt: "Brasão", en: "Frill", price: 125 },
  { id: 7054, pt: "Brigan", en: "Brigan", price: 373 },
  { id: 7708, pt: "Broken Apple Juice", en: "Broken Apple Juice", price: 10 },
  { id: 7707, pt: "Broken Banana Juice", en: "Broken Banana Juice", price: 10 },
  { id: 7706, pt: "Broken Carrot Juice", en: "Broken Carrot Juice", price: 10 },
  { id: 7709, pt: "Broken Grape Juice", en: "Broken Grape Juice", price: 10 },
  { id: 711, pt: "Broto", en: "Shoot", price: 8 },
  { id: 744, pt: "Buquê", en: "Bouquet", price: 1000 },
  { id: 745, pt: "Buquê de Casamento", en: "Wedding Bouquet", price: 6000 },
  { id: 1034, pt: "Cabelo Azul", en: "Blue Hair", price: 171 },
  { id: 1048, pt: "Cabelo Horrendo", en: "Horrendous Hair", price: 400 },
  { id: 1060, pt: "Cabelos Dourados", en: "Golden Hair", price: 215 },
  { id: 1020, pt: "Cabelos Morenos", en: "Black Hair", price: 146 },
  { id: 7152, pt: "Cabelos Perfumados", en: "Glossy Hair", price: 170 },
  { id: 7443, pt: "Cabeça de Dragão de Três Cabeças", en: "Three-Headed Dragon's Head", price: 478 },
  { id: 7607, pt: "Cabeça de Dragão Maligno", en: "Neck of Demon Dragon", price: 5 },
  { id: 1047, pt: "Cabeça de Medusa", en: "Dead Medusa", price: 274 },
  { id: 7182, pt: "Cacau", en: "Cacao", price: 100 },
  { id: 7216, pt: "Cachecol Vermelho", en: "Red Muffler", price: 330 },
  { id: 6331, pt: "Calender April", en: "Calender April", price: 10 },
  { id: 6335, pt: "Calender August", en: "Calender August", price: 10 },
  { id: 6339, pt: "Calender December", en: "Calender December", price: 10 },
  { id: 6329, pt: "Calender February", en: "Calender February", price: 10 },
  { id: 6328, pt: "Calender January", en: "Calender January", price: 10 },
  { id: 6334, pt: "Calender July", en: "Calender July", price: 10 },
  { id: 6333, pt: "Calender June", en: "Calender June", price: 10 },
  { id: 6330, pt: "Calender March", en: "Calender March", price: 10 },
  { id: 6332, pt: "Calender May", en: "Calender May", price: 10 },
  { id: 6338, pt: "Calender November", en: "Calender November", price: 10 },
  { id: 6337, pt: "Calender October", en: "Calender October", price: 10 },
  { id: 6336, pt: "Calender September", en: "Calender September", price: 10 },
  { id: 1035, pt: "Canino de Dragão", en: "Dragon Canine", price: 242 },
  { id: 937, pt: "Canino Venenoso", en: "Venom Canine", price: 74 },
  { id: 966, pt: "Carne de Ostra", en: "Clam Flesh", price: 79 },
  { id: 6249, pt: "Carne de Selvagem", en: "Savage Meat", price: 50 },
  { id: 7564, pt: "Carne Estragada", en: "Rotten Meat", price: 51 },
  { id: 6223, pt: "Carnium", en: "Carnium", price: 1000 },
  { id: 7217, pt: "Carretel", en: "Spool", price: 212 },
  { id: 7978, pt: "Cartão Chinês 1", en: "Spring Stanza1", price: 1 },
  { id: 7987, pt: "Cartão Chinês 10", en: "Spring Stanza10", price: 1 },
  { id: 7988, pt: "Cartão Chinês 11", en: "Spring Stanza11", price: 1 },
  { id: 7989, pt: "Cartão Chinês 12", en: "Spring Stanza12", price: 1 },
  { id: 7990, pt: "Cartão Chinês 13", en: "Spring Stanza13", price: 1 },
  { id: 7991, pt: "Cartão Chinês 14", en: "Spring Stanza14", price: 1 },
  { id: 7992, pt: "Cartão Chinês 15", en: "Spring Stanza15", price: 1 },
  { id: 7993, pt: "Cartão Chinês 16", en: "Spring Stanza16", price: 1 },
  { id: 7994, pt: "Cartão Chinês 17", en: "Spring Stanza17", price: 1 },
  { id: 7995, pt: "Cartão Chinês 18", en: "Spring Stanza18", price: 1 },
  { id: 7996, pt: "Cartão Chinês 19", en: "Spring Stanza19", price: 1 },
  { id: 7979, pt: "Cartão Chinês 2", en: "Spring Stanza2", price: 1 },
  { id: 7997, pt: "Cartão Chinês 20", en: "Spring Stanza20", price: 1 },
  { id: 7998, pt: "Cartão Chinês 21", en: "Spring Stanza21", price: 1 },
  { id: 7999, pt: "Cartão Chinês 22", en: "Spring Stanza22", price: 1 },
  { id: 7624, pt: "Cartão Chinês 23", en: "Spring Stanza23", price: 1 },
  { id: 7980, pt: "Cartão Chinês 3", en: "Spring Stanza3", price: 1 },
  { id: 7981, pt: "Cartão Chinês 4", en: "Spring Stanza4", price: 1 },
  { id: 7982, pt: "Cartão Chinês 5", en: "Spring Stanza5", price: 1 },
  { id: 7983, pt: "Cartão Chinês 6", en: "Spring Stanza6", price: 1 },
  { id: 7984, pt: "Cartão Chinês 7", en: "Spring Stanza7", price: 1 },
  { id: 7985, pt: "Cartão Chinês 8", en: "Spring Stanza8", price: 1 },
  { id: 7986, pt: "Cartão Chinês 9", en: "Spring Stanza9", price: 1 },
  { id: 7348, pt: "Cartão de Sócio", en: "Membership Card", price: 10 },
  { id: 1003, pt: "Carvão", en: "Coal", price: 250 },
  { id: 6251, pt: "Carvão Negro", en: "Black Charcoal", price: 150 },
  { id: 935, pt: "Casca", en: "Shell", price: 7 },
  { id: 1096, pt: "Casca Arredondada", en: "Round Shell", price: 390 },
  { id: 7009, pt: "Casca Brilhante", en: "Glitter Shell", price: 264 },
  { id: 7062, pt: "Casca de Tartaruga", en: "Broken Turtle Shell", price: 140 },
  { id: 936, pt: "Casca Escamada", en: "Scale Shell", price: 233 },
  { id: 7070, pt: "Casca Quebrada", en: "Broken Shell", price: 450 },
  { id: 943, pt: "Casca Rija", en: "Solid Shell", price: 224 },
  { id: 1013, pt: "Casco Arco-Íris", en: "Rainbow Shell", price: 45 },
  { id: 946, pt: "Casco de Caramujo", en: "Snail's Shell", price: 32 },
  { id: 964, pt: "Casco de Caranguejo", en: "Crab Shell", price: 45 },
  { id: 7190, pt: "Casco de Inseto", en: "Solid Husk", price: 70 },
  { id: 965, pt: "Casco de Ostra", en: "Clam Shell", price: 28 },
  { id: 967, pt: "Casco de Tartaruga", en: "Turtle Shell", price: 340 },
  { id: 7192, pt: "Catavento", en: "Vane", price: 80 },
  { id: 1037, pt: "Cauda de Dragão", en: "Dragon Tail", price: 600 },
  { id: 904, pt: "Cauda de Escorpião", en: "Scorpion Tail", price: 62 },
  { id: 7010, pt: "Cauda de Escorpião de Aço", en: "Tail of Steel Scorpion", price: 274 },
  { id: 1023, pt: "Cauda de Peixe", en: "Fish Tail", price: 98 },
  { id: 1016, pt: "Cauda de Rato", en: "Rat Tail", price: 26 },
  { id: 942, pt: "Cauda de Yoyo", en: "Yoyo Tail", price: 57 },
  { id: 905, pt: "Caule", en: "Stem", price: 23 },
  { id: 7581, pt: "Celebration Document", en: "Celebration Document", price: 10 },
  { id: 7299, pt: "Cesto de Palha", en: "Straw Basket", price: 316 },
  { id: 7113, pt: "Cetro do Faraó", en: "Broken Pharaoh Emblem", price: 1008 },
  { id: 7323, pt: "Chaleira Surrada", en: "Battered Kettle", price: 128 },
  { id: 6021, pt: "Chapéu Pontudo", en: "Peaked Hat", price: 216 },
  { id: 7567, pt: "Chapéu Suspeito", en: "Suspicious Hat", price: 645 },
  { id: 7892, pt: "Charcoal", en: "Charcoal", price: 5 },
  { id: 6186, pt: "Chave Inglesa", en: "Monkey Wrench", price: 250 },
  { id: 7026, pt: "Chave para a Torre do Relógio", en: "Key of Clock Tower", price: 50 },
  { id: 7027, pt: "Chave para o Subterrâneo", en: "Key of Underground", price: 50 },
  { id: 947, pt: "Chifre", en: "Horn", price: 58 },
  { id: 7106, pt: "Chifre de Bode", en: "Antelope Horn", price: 336 },
  { id: 1021, pt: "Chifre de Dokebi", en: "Dokebi Horn", price: 146 },
  { id: 7265, pt: "Chifre de Dragão", en: "Dragon Horn", price: 272 },
  { id: 6032, pt: "Chifre de Leão da Montanha", en: "Horn of Hillslion", price: 250 },
  { id: 6033, pt: "Chifre de Leão de Vinhas", en: "Horn of Tendrilion", price: 250 },
  { id: 923, pt: "Chifre Diabólico", en: "Evil Horn", price: 600 },
  { id: 7008, pt: "Chifre Firme", en: "Stiff Horn", price: 318 },
  { id: 6023, pt: "Chifre Místico", en: "Mystic Horn", price: 500 },
  { id: 735, pt: "Chung Jah", en: "Chung Jah", price: 2500 },
  { id: 7822, pt: "Churrasco Selvagem", en: "Whole Barbecue", price: 10 },
  { id: 7548, pt: "Chuteiras", en: "Soccer Shoes", price: 10 },
  { id: 7186, pt: "Cipó", en: "Thin Trunk", price: 190 },
  { id: 6053, pt: "Circle Step", en: "Circle Step", price: 50 },
  { id: 7295, pt: "Citrina", en: "Citrin", price: 1500 },
  { id: 7750, pt: "Cocada Cremosa", en: "Macapuno", price: 1 },
  { id: 6263, pt: "Coco Fresco", en: "Coconut Fruit", price: 50 },
  { id: 7055, pt: "Cocô de Bichinho", en: "Animal Poop", price: 50 },
  { id: 1070, pt: "Cogumelo Borrachento", en: "Orange Gooey Mushroom", price: 1 },
  { id: 1069, pt: "Cogumelo Venenoso", en: "Orange Net Mushroom", price: 1 },
  { id: 1007, pt: "Colar da Sabedoria", en: "Necklace of Wisdom", price: 1 },
  { id: 1008, pt: "Colar do Oblívio", en: "Necklace of Oblivion", price: 1 },
  { id: 7016, pt: "Colher Entortada", en: "Spoon Stub", price: 1250 },
  { id: 7222, pt: "Coluna de Madeira", en: "Wooden Gnarl", price: 234 },
  { id: 6146, pt: "Combustível Diferenciado Leve", en: "Magic Gear Fuel", price: 150 },
  { id: 11024, pt: "Como Aumentar sua Energia", en: "Vital Drink CB", price: 5 },
  { id: 11023, pt: "Como Aumentar sua Força", en: "Increase Stamina Study", price: 5 },
  { id: 7747, pt: "Compota de Laranja", en: "Langka", price: 1 },
  { id: 961, pt: "Concha", en: "Conch", price: 79 },
  { id: 737, pt: "Concha Preta", en: "Black Ladle", price: 200 },
  { id: 7452, pt: "Condimento Amarelo", en: "Yellow Spice", price: 500 },
  { id: 7456, pt: "Condimento Vermelho", en: "Red Spice", price: 500 },
  { id: 6222, pt: "Conta Brilhante", en: "Shining Beads", price: 10 },
  { id: 6107, pt: "Coquetel de Verão", en: "Sunset On The Rock", price: 10 },
  { id: 7013, pt: "Coral", en: "Coral Reef", price: 386 },
  { id: 7189, pt: "Coração de Madeira", en: "Wooden Heart", price: 340 },
  { id: 953, pt: "Coração de Pedra", en: "Stone Heart", price: 92 },
  { id: 950, pt: "Coração de Sereia", en: "Heart of Mermaid", price: 132 },
  { id: 994, pt: "Coração Flamejante", en: "Flame Heart", price: 1500 },
  { id: 7561, pt: "Coração Glacial", en: "Glacial Heart", price: 303 },
  { id: 929, pt: "Coração Imortal", en: "Immortal Heart", price: 187 },
  { id: 7097, pt: "Coração Incandescente", en: "Burning Heart", price: 462 },
  { id: 7218, pt: "Corda Decomposta", en: "Decomposed Rope", price: 195 },
  { id: 7870, pt: "Corn", en: "Corn", price: 2 },
  { id: 7754, pt: "Coroa Quebrada", en: "Broken Crown", price: 1500 },
  { id: 7221, pt: "Corrente", en: "Tangled Chains", price: 370 },
  { id: 919, pt: "Couro de Animal", en: "Animal Skin", price: 18 },
  { id: 1028, pt: "Crina", en: "Mane", price: 98 },
  { id: 6087, pt: "Crista Espiritual Azul", en: "Spiritual Crystal", price: 525 },
  { id: 6088, pt: "Crista Espiritual Vermelha", en: "Spiritual Crystal", price: 525 },
  { id: 7578, pt: "Cristal Anti-Magia", en: "Countermagic Crystal", price: 10 },
  { id: 991, pt: "Cristal Azul", en: "Crystal Blue", price: 500 },
  { id: 7799, pt: "Cristal da Escuridão", en: "Crystal of Darkness", price: 5 },
  { id: 6098, pt: "Cristal de Neve", en: "Small Snow Flower", price: 500 },
  { id: 7289, pt: "Cristal de Peridoto", en: "Peridot", price: 1500 },
  { id: 6104, pt: "Cristal Gigante", en: "Big Cell", price: 500 },
  { id: 915, pt: "Crisálida", en: "Chrysalis", price: 4 },
  { id: 7405, pt: "Crushed Can", en: "Crushed Can", price: 1 },
  { id: 7005, pt: "Crânio", en: "Skull", price: 522 },
  { id: 7752, pt: "Crânio Atordoante", en: "Clattering Skull", price: 420 },
  { id: 7066, pt: "Cubo de Gelo", en: "Ice Cubic", price: 330 },
  { id: 6188, pt: "Cupom de Slot", en: "Slotting Advertisement", price: 10 },
  { id: 7053, pt: "Cyfar", en: "Cyfar", price: 386 },
  { id: 7143, pt: "Cápsula da Criação", en: "Glass Tube", price: 2500 },
  { id: 6147, pt: "Cápsula de Nitrogênio Líquido", en: "Liquid Condensed Bullet", price: 50 },
  { id: 6145, pt: "Cápsula Incandescente", en: "Vulcan Bullet", price: 5 },
  { id: 1052, pt: "Célula Única", en: "Single Cell", price: 23 },
  { id: 7266, pt: "Dentadura da Máscara do Dragão", en: "Denture from Dragon Mask", price: 218 },
  { id: 913, pt: "Dente de Morcego", en: "Tooth of Bat", price: 17 },
  { id: 7002, pt: "Dente de Ogro", en: "Ogre Tooth", price: 329 },
  { id: 1053, pt: "Dente Fossilizado", en: "Ancient Tooth", price: 274 },
  { id: 7340, pt: "Desejo das Trevas", en: "Will of the Darkness", price: 367 },
  { id: 7566, pt: "Desejo das Trevas Escarlate", en: "Will of Red Darkness", price: 765 },
  { id: 971, pt: "Detrimindexta", en: "Detrimindexta", price: 200 },
  { id: 7723, pt: "Diamante da Ruína", en: "Diamond of Ruin", price: 10 },
  { id: 730, pt: "Diamante de 1 quilate", en: "1carat Diamond", price: 5000 },
  { id: 731, pt: "Diamante de 2 quilates", en: "2carat Diamond", price: 12500 },
  { id: 732, pt: "Diamante de 3 quilates", en: "3carat Diamond", price: 27500 },
  { id: 733, pt: "Diamante Rachado", en: "Cracked Diamond", price: 5 },
  { id: 11008, pt: "Dicionário Biográfico", en: "Biographical Dictionary Copy Edition", price: 5000 },
  { id: 7351, pt: "Diário do Amigo", en: "Friend's Diary", price: 10 },
  { id: 7749, pt: "Doce de Banana", en: "Sweet Bananas", price: 1 },
  { id: 7745, pt: "Doce de Batata-Doce", en: "Ube Jam", price: 1 },
  { id: 7748, pt: "Doce de Feijão", en: "Sweet Beans", price: 1 },
  { id: 7746, pt: "Doce de Tapioca", en: "Sago", price: 1 },
  { id: 6314, pt: "E Enriched Elunium", en: "E Enriched Elunium", price: 1 },
  { id: 6315, pt: "E Enriched Oridecon", en: "E Enriched Oridecon", price: 1 },
  { id: 6515, pt: "Earth Amulet", en: "Earth Amulet", price: 50 },
  { id: 7220, pt: "Ectoplasma", en: "Ectoplasm", price: 161 },
  { id: 7209, pt: "Elmo de Dullahan", en: "Helm of Dullahan", price: 675 },
  { id: 985, pt: "Elunium", en: "Elunium", price: 550 },
  { id: 7619, pt: "Elunium Enriquecido", en: "Enriched Elunium", price: 1 },
  { id: 6241, pt: "Elunium Perfeito", en: "HD Elunium", price: 10 },
  { id: 7200, pt: "Elástico", en: "Elastic Band", price: 190 },
  { id: 7142, pt: "Embrião", en: "Embryo", price: 5 },
  { id: 714, pt: "Emperium", en: "Emperium", price: 1 },
  { id: 1011, pt: "Emveretarcon", en: "Emveretarcon", price: 500 },
  { id: 7093, pt: "Engrenagem", en: "Cogwheel", price: 756 },
  { id: 7763, pt: "Erva Grudenta", en: "Sticky Herb", price: 10 },
  { id: 906, pt: "Escama Afiada", en: "Pointed Scale", price: 34 },
  { id: 963, pt: "Escama Aquática", en: "Sharp Scale", price: 125 },
  { id: 954, pt: "Escama Brilhante", en: "Shining Scale", price: 233 },
  { id: 1036, pt: "Escama de Dragão", en: "Dragon Scale", price: 250 },
  { id: 7451, pt: "Escama de Dragão de Fogo", en: "Fire Dragon Scale", price: 926 },
  { id: 7562, pt: "Escama de Gelo", en: "Ice Scale", price: 1510 },
  { id: 959, pt: "Escama Fétida", en: "Stinky Scale", price: 84 },
  { id: 6091, pt: "Escama Vermelha-Escura", en: "Dark Red Scale", price: 100000 },
  { id: 926, pt: "Escamas de Cobra", en: "Snake Scale", price: 41 },
  { id: 7524, pt: "Esfera das Sombras", en: "Shadow Orb", price: 150 },
  { id: 7858, pt: "Esfera Mágica Amarela", en: "Dragonball Yellow", price: 10 },
  { id: 721, pt: "Esmeralda", en: "Emerald", price: 3000 },
  { id: 7725, pt: "Esmeralda dos Azarados", en: "Unlucky Emerald", price: 10 },
  { id: 7110, pt: "Espada Chanfrada", en: "Broken Sword", price: 294 },
  { id: 747, pt: "Espelho de Cristal", en: "Crystal Mirror", price: 7500 },
  { id: 7823, pt: "Espetinho Vegetariano", en: "Meat Veg Skewer", price: 10 },
  { id: 6250, pt: "Espeto de Cozinha", en: "Cooking Skewer", price: 150 },
  { id: 7215, pt: "Espeto Quebrado", en: "Broken Needle", price: 345 },
  { id: 952, pt: "Espinho de Cacto", en: "Cactus Needle", price: 41 },
  { id: 1027, pt: "Espinho de Porco-Espinho", en: "Porcupine Quill", price: 79 },
  { id: 921, pt: "Esporo de Cogumelo", en: "Mushroom Spore", price: 18 },
  { id: 6212, pt: "Esporo de Cogumelo Explosivo", en: "Bomb Mushroom Spore", price: 500 },
  { id: 7033, pt: "Esporo Venenoso", en: "Poison Spore", price: 57 },
  { id: 7701, pt: "Espírito de Dragão", en: "Soul", price: 1 },
  { id: 934, pt: "Espólio", en: "Memento", price: 300 },
  { id: 7724, pt: "Esquecida Arte Secreta", en: "Forbidden Secret Art", price: 10 },
  { id: 7921, pt: "Essence Of Dragon", en: "Essence Of Dragon", price: 500 },
  { id: 7103, pt: "Essência de AXE", en: "Unknown Liquid Bottle", price: 5 },
  { id: 7195, pt: "Estilingue", en: "Slingshot", price: 105 },
  { id: 738, pt: "Estojo de Lápis", en: "Pencil Case", price: 200 },
  { id: 6300, pt: "event", en: "event", price: 10 },
  { id: 6301, pt: "event", en: "event", price: 10 },
  { id: 6291, pt: "F Enriched Elunium", en: "F Enriched Elunium", price: 1 },
  { id: 6292, pt: "F Enriched Oridecon", en: "F Enriched Oridecon", price: 1 },
  { id: 7208, pt: "Faca Enferrujada", en: "Rusty Kitchen Knife", price: 890 },
  { id: 7071, pt: "Farrapos", en: "Tattered Clothes", price: 640 },
  { id: 914, pt: "Felpa", en: "Fluff", price: 4 },
  { id: 944, pt: "Ferradura", en: "Horseshoe", price: 294 },
  { id: 7120, pt: "Ferradura em Chamas", en: "Burning Horseshoe", price: 411 },
  { id: 998, pt: "Ferro", en: "Iron", price: 50 },
  { id: 939, pt: "Ferrão de Abelha", en: "Bee Sting", price: 16 },
  { id: 6381, pt: "Field Shovel", en: "Field Shovel", price: 10 },
  { id: 6512, pt: "Fire Amulet", en: "Fire Amulet", price: 50 },
  { id: 7301, pt: "Fitilhos", en: "Tassel", price: 399 },
  { id: 6124, pt: "Flauta Uivante", en: "Wolf Flute", price: 5 },
  { id: 7290, pt: "Flogopita", en: "Phlogopite", price: 1500 },
  { id: 712, pt: "Flor", en: "Flower", price: 1 },
  { id: 7331, pt: "Flor Celestial", en: "Heaven Flower", price: 250 },
  { id: 710, pt: "Flor das Ilusões", en: "Illusion Flower", price: 500 },
  { id: 1032, pt: "Flor de Planta Carnívora", en: "Maneater Blossom", price: 98 },
  { id: 7510, pt: "Flor de Valhalla", en: "Valhalla's Flower", price: 100000 },
  { id: 7864, pt: "Flor do Amor", en: "Love Flower", price: 10 },
  { id: 6086, pt: "Flor Murcha", en: "Withered Flower", price: 445 },
  { id: 6113, pt: "Flor Vital", en: "Vital Flower", price: 500 },
  { id: 6110, pt: "Flor Vívida", en: "Vital Flower", price: 500 },
  { id: 11006, pt: "Flores de Sangue Vol.1", en: "Blood Flower Vol.1", price: 4000 },
  { id: 11007, pt: "Flores de Sangue Vol.2", en: "Blood Flower Vol.2", price: 4000 },
  { id: 1031, pt: "Foice de Louva-a-Deus", en: "Mantis Scythe", price: 98 },
  { id: 7100, pt: "Folha Afiada", en: "Sharp Leaf", price: 403 },
  { id: 7298, pt: "Folha de Figo", en: "Fig Leaf", price: 269 },
  { id: 945, pt: "Folha de Fumacento", en: "Raccoon Leaf", price: 53 },
  { id: 7526, pt: "Folha de Manuscrito", en: "Manuscript Paper", price: 1 },
  { id: 7198, pt: "Folha Gigante", en: "Huge Leaf", price: 305 },
  { id: 6357, pt: "Fortune Cookie Fail", en: "Fortune Cookie Fail", price: 2010 },
  { id: 7458, pt: "Fortune Horn", en: "Fortune Horn", price: 1 },
  { id: 1010, pt: "Fracon", en: "Phracon", price: 100 },
  { id: 7918, pt: "Fragment Of Memory", en: "Fragment Of Memory", price: 1000 },
  { id: 6362, pt: "Fragmento Amarelo", en: "Yellow Wish Point", price: 50 },
  { id: 6361, pt: "Fragmento Azul", en: "Indigo Point", price: 50 },
  { id: 7798, pt: "Fragmento da Escuridão", en: "Fragment of Darkness", price: 250 },
  { id: 7436, pt: "Fragmento de Agonia", en: "Fragment of Agony", price: 753 },
  { id: 7439, pt: "Fragmento de Desespero", en: "Fragment of Despair", price: 753 },
  { id: 7437, pt: "Fragmento de Desgraça", en: "Fragment of Misery", price: 753 },
  { id: 7438, pt: "Fragmento de Ódio", en: "Fragment of Hatred", price: 753 },
  { id: 6360, pt: "Fragmento Escarlate", en: "Scarlet Point", price: 50 },
  { id: 1000, pt: "Fragmento Estelar", en: "Star Crumb", price: 2250 },
  { id: 7094, pt: "Fragmento Misterioso", en: "Fragment", price: 672 },
  { id: 6089, pt: "Fragmento Sombrio", en: "Dark Piece", price: 500 },
  { id: 6363, pt: "Fragmento Verde", en: "Lime Green Point", price: 50 },
  { id: 7138, pt: "Frasco de Esfera Marinha", en: "Marine Sphere Bottle", price: 100 },
  { id: 7135, pt: "Frasco de Fogo Grego", en: "Bottle Grenade", price: 100 },
  { id: 7137, pt: "Frasco de Planta Carnívora", en: "Plant Bottle", price: 100 },
  { id: 7139, pt: "Frasco de Revestimento", en: "Glistening Coat", price: 100 },
  { id: 7136, pt: "Frasco de Ácido", en: "Acid Bottle", price: 100 },
  { id: 992, pt: "Frescor do Vento", en: "Wind of Verdure", price: 500 },
  { id: 6112, pt: "Fresh Plant", en: "Fresh Plant", price: 500 },
  { id: 7868, pt: "Fresh Water", en: "Fresh Water", price: 5 },
  { id: 6258, pt: "Fruta de Comodo", en: "Comodo Tropical Fruit", price: 400 },
  { id: 6100, pt: "Fumaça Negra", en: "Damp Darkness", price: 500 },
  { id: 7214, pt: "Gaiola de Morcegos", en: "Bat Cage", price: 440 },
  { id: 7939, pt: "Galho Antigo", en: "Elder Branch", price: 500 },
  { id: 7203, pt: "Galho Resistente", en: "Strong Branch", price: 95 },
  { id: 910, pt: "Garleta", en: "Garlet", price: 20 },
  { id: 917, pt: "Garra de Ave", en: "Talon", price: 10 },
  { id: 960, pt: "Garra de Crustáceo", en: "Nipper", price: 57 },
  { id: 1046, pt: "Garra de Escorpião", en: "Scorpion Nipper", price: 307 },
  { id: 7048, pt: "Garra de Grifo", en: "Talon of Griffon", price: 2709 },
  { id: 7116, pt: "Garra de Harpia", en: "Harpy Talon", price: 605 },
  { id: 920, pt: "Garra de Lobo", en: "Wolf Claw", price: 29 },
  { id: 7030, pt: "Garra de Lobo do Deserto", en: "Claw of Desert Wolf", price: 104 },
  { id: 7011, pt: "Garra de Macaco", en: "Claw of Monkey", price: 233 },
  { id: 1043, pt: "Garra de Orc", en: "Orc Claw", price: 84 },
  { id: 7007, pt: "Garra de Rato", en: "Claw of Rat", price: 374 },
  { id: 6216, pt: "Garrafa com Óleo", en: "Oil Bottle", price: 500 },
  { id: 6297, pt: "Garrafa de Arremesso", en: "Throwing Bottle", price: 150 },
  { id: 7761, pt: "Garrafa de Magia", en: "Magic Gourd Bottle", price: 10 },
  { id: 1093, pt: "Garrafa de Poção", en: "Empty Potion Bottle", price: 5 },
  { id: 713, pt: "Garrafa Vazia", en: "Empty Bottle", price: 3 },
  { id: 7172, pt: "Garras de Leopardo", en: "Leopard Claw", price: 145 },
  { id: 1018, pt: "Garras de Toupeira", en: "Mole Claw", price: 105 },
  { id: 6108, pt: "Gelatina de Maçã", en: "Apple Pudding", price: 500 },
  { id: 6253, pt: "Gelo", en: "Cold Ice", price: 50 },
  { id: 6257, pt: "Gelo Cristalino", en: "Ice Crystal", price: 50 },
  { id: 995, pt: "Gelo Místico", en: "Mystic Frozen", price: 1500 },
  { id: 7743, pt: "Geléia de Morango", en: "Gulaman", price: 1 },
  { id: 715, pt: "Gema Amarela", en: "Yellow Gemstone", price: 300 },
  { id: 717, pt: "Gema Azul", en: "Blue Gemstone", price: 300 },
  { id: 7582, pt: "Gema da Ruína", en: "Jewel of Destruction", price: 5 },
  { id: 6114, pt: "Gema em Chamas", en: "Flame Gemstone", price: 500 },
  { id: 716, pt: "Gema Vermelha", en: "Red Gemstone", price: 300 },
  { id: 7759, pt: "Geologist's Report", en: "Geologist's Report", price: 10 },
  { id: 7856, pt: "Girl's Bouquet", en: "Girl's Bouquet", price: 10 },
  { id: 6302, pt: "GM Handwriting", en: "GM Handwriting", price: 10002 },
  { id: 7865, pt: "Gold Pouch", en: "Gold Pouch", price: 5 },
  { id: 6394, pt: "Golden Feather", en: "Golden Feather", price: 325 },
  { id: 7951, pt: "Golden Tulip Flower", en: "Golden Tulip Flower", price: 5 },
  { id: 7194, pt: "Grama", en: "Soft Blade of Grass", price: 200 },
  { id: 718, pt: "Granada", en: "Garnet", price: 3000 },
  { id: 7168, pt: "Grandes Asas de Borboleta", en: "Giant Butterfly Wing", price: 307 },
  { id: 7018, pt: "Graveto de Visco", en: "Young Twig", price: 25 },
  { id: 6099, pt: "Grilled Rice Cake", en: "Grilled Rice Cake", price: 10 },
  { id: 7584, pt: "Guard's First Proof", en: "Guard's First Proof", price: 5 },
  { id: 7587, pt: "Guard's Fourth Proof", en: "Guard's Fourth Proof", price: 5 },
  { id: 7585, pt: "Guard's Second Proof", en: "Guard's Second Proof", price: 5 },
  { id: 7586, pt: "Guard's Third Proof", en: "Guard's Third Proof", price: 5 },
  { id: 956, pt: "Guelra", en: "Gill", price: 171 },
  { id: 7419, pt: "Guia de Criação de Embriões", en: "Embryo Creation Guide", price: 24000 },
  { id: 7434, pt: "Guia de Criação de Poções Elementais", en: "Elemental Potion Creation Guide", price: 50000 },
  { id: 11049, pt: "Gun Book Basic", en: "Gun Book Basic", price: 10 },
  { id: 11051, pt: "Gun Book Misc", en: "Gun Book Misc", price: 10 },
  { id: 11050, pt: "Gun Book Practice", en: "Gun Book Practice", price: 10 },
  { id: 6214, pt: "Gás de Fumaça", en: "Smoke Powder", price: 250 },
  { id: 6215, pt: "Gás Lacrimejante", en: "Tear Gas", price: 250 },
  { id: 7322, pt: "Gás Tóxico", en: "Toxic Gas", price: 333 },
  { id: 7857, pt: "Hand-made Kitty Doll", en: "Hand-made Kitty Doll", price: 10 },
  { id: 7400, pt: "Hari", en: "Hari", price: 1 },
  { id: 7855, pt: "Heart", en: "Heart", price: 10 },
  { id: 7612, pt: "Heart of Queen Fox", en: "Heart of Queen Fox", price: 1 },
  { id: 7872, pt: "Herb", en: "Herb", price: 5 },
  { id: 703, pt: "Hinalle", en: "Hinalle", price: 250 },
  { id: 11000, pt: "História de Prontera", en: "History book of Prontera", price: 4000 },
  { id: 11001, pt: "Histórias de Aventura Vol.1", en: "Adventure Story Vol.1", price: 4000 },
  { id: 11009, pt: "Histórias de Aventura Vol.2", en: "Adventure Story Vol.2", price: 4000 },
  { id: 6513, pt: "Ice Amulet", en: "Ice Amulet", price: 50 },
  { id: 7459, pt: "Idul Fitri Card", en: "Idul Fitri Card", price: 1 },
  { id: 7973, pt: "Immortality Egg", en: "Immortality Egg", price: 10 },
  { id: 7403, pt: "Indonesia", en: "Indonesia", price: 1 },
  { id: 1004, pt: "Insígnia da Cavalaria", en: "Chivalry Emblem", price: 1 },
  { id: 968, pt: "Insígnia do Herói", en: "Heroic Emblem", price: 1500 },
  { id: 709, pt: "Izidor", en: "Izidor", price: 250 },
  { id: 11020, pt: "Japan Book1", en: "Japan Book1", price: 10 },
  { id: 11021, pt: "Japan Book2", en: "Japan Book2", price: 10 },
  { id: 7162, pt: "Jarro de Nuvem", en: "Cloud Crumb", price: 195 },
  { id: 7158, pt: "Jarro de Saquê", en: "Broken Liquor Jar", price: 80 },
  { id: 909, pt: "Jellopy", en: "Jellopy", price: 3 },
  { id: 7126, pt: "Jellopy Tamanho Família", en: "Large Jellopy", price: 420 },
  { id: 7312, pt: "Jubileu", en: "Jubilee", price: 16 },
  { id: 7576, pt: "Jóia Azul", en: "Blue Jewel", price: 10 },
  { id: 7577, pt: "Jóia Dourada", en: "Yellow Jewel", price: 10 },
  { id: 7575, pt: "Jóia Vermelha", en: "Red Jewel", price: 10 },
  { id: 972, pt: "Karvodailnirol", en: "Karvodailnirol", price: 200 },
  { id: 7404, pt: "Ke-60", en: "Ke-60", price: 1 },
  { id: 7401, pt: "Kemerdekaan", en: "Kemerdekaan", price: 1 },
  { id: 7302, pt: "Krathong", en: "Krathong", price: 1 },
  { id: 7025, pt: "Lamento de Lúcifer", en: "Lucifer's Lament", price: 15000 },
  { id: 1041, pt: "Lampião", en: "Lantern", price: 125 },
  { id: 7225, pt: "Lanterna de Abóbora", en: "Pumpkin Lantern", price: 243 },
  { id: 7327, pt: "Lanterna de Capacete", en: "Flashlight", price: 512 },
  { id: 7211, pt: "Lasca de Pedra", en: "Fragment of Rossata Stone", price: 1300 },
  { id: 6068, pt: "Leather Rabbit", en: "Leather Rabbit", price: 5 },
  { id: 11003, pt: "Lendas das Kafras Vol.1", en: "Kafra Legend Vol.1", price: 4000 },
  { id: 7098, pt: "Lenha em Brasa", en: "Live Coal", price: 319 },
  { id: 7262, pt: "Leque Fantasma", en: "Folding Fan of Cat Ghost", price: 233 },
  { id: 6062, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 6063, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 6064, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 6065, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 6066, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 6067, pt: "Letter Moon Cake", en: "Letter Moon Cake", price: 5 },
  { id: 7589, pt: "Lettered Moon Snack 01", en: "Lettered Moon Snack 01", price: 10 },
  { id: 7590, pt: "Lettered Moon Snack 02", en: "Lettered Moon Snack 02", price: 10 },
  { id: 7591, pt: "Lettered Moon Snack 03", en: "Lettered Moon Snack 03", price: 10 },
  { id: 7592, pt: "Lettered Moon Snack 04", en: "Lettered Moon Snack 04", price: 10 },
  { id: 7593, pt: "Lettered Moon Snack 05", en: "Lettered Moon Snack 05", price: 10 },
  { id: 6377, pt: "Licença de Atacado", en: "Buy Market Permit", price: 10 },
  { id: 7287, pt: "Linha Abençoada", en: "Holier Threads", price: 1 },
  { id: 7285, pt: "Linha Sagrada", en: "Holy Threads", price: 1 },
  { id: 7722, pt: "Lista de Débitos", en: "Debt Note", price: 10 },
  { id: 6280, pt: "Livro de Bombas de Abacaxi", en: "Pineapple Bomb Guidebook", price: 500 },
  { id: 6283, pt: "Livro de Bombas de Banana", en: "Banana Bomb Guidebook", price: 500 },
  { id: 6281, pt: "Livro de Bombas de Coco", en: "Coconut Fruit Bomb Guidebook", price: 500 },
  { id: 6279, pt: "Livro de Bombas de Maçã", en: "Apple Bomb Guidebook", price: 500 },
  { id: 6282, pt: "Livro de Bombas de Melão", en: "Melon Bomb Guidebook", price: 500 },
  { id: 11022, pt: "Livro de Culinária Avançada", en: "Mix Cook Book", price: 5 },
  { id: 7472, pt: "Livro de Culinária Nível 1", en: "Level 1 Cookbook", price: 500 },
  { id: 7481, pt: "Livro de Culinária Nível 10", en: "Level 10 Cookbook", price: 500 },
  { id: 7473, pt: "Livro de Culinária Nível 2", en: "Level 2 Cookbook", price: 500 },
  { id: 7474, pt: "Livro de Culinária Nível 3", en: "Level 3 Cookbook", price: 500 },
  { id: 7475, pt: "Livro de Culinária Nível 4", en: "Level 4 Cookbook", price: 500 },
  { id: 7476, pt: "Livro de Culinária Nível 5", en: "Level 5 Cookbook", price: 500 },
  { id: 7477, pt: "Livro de Culinária Nível 6", en: "Level 6 Cookbook", price: 500 },
  { id: 7478, pt: "Livro de Culinária Nível 7", en: "Level 7 Cookbook", price: 500 },
  { id: 7479, pt: "Livro de Culinária Nível 8", en: "Level 8 Cookbook", price: 500 },
  { id: 7480, pt: "Livro de Culinária Nível 9", en: "Level 9 Cookbook", price: 500 },
  { id: 6284, pt: "Livro de Genética Vegetal", en: "How To Grow Plant Genes", price: 500 },
  { id: 7756, pt: "Livro Lacrado", en: "Sealed Book", price: 1000 },
  { id: 7760, pt: "Livro Mágico de Yaga", en: "Yaga's Magic Book", price: 10 },
  { id: 6383, pt: "Lope's Clue", en: "Lope's Clue", price: 10 },
  { id: 7955, pt: "Lost Card1", en: "Lost Card1", price: 5 },
  { id: 7956, pt: "Lost Card2", en: "Lost Card2", price: 5 },
  { id: 7957, pt: "Lost Card3", en: "Lost Card3", price: 5 },
  { id: 7958, pt: "Lost Card4", en: "Lost Card4", price: 5 },
  { id: 7017, pt: "Luva do Carrasco", en: "Executioner's Mitten", price: 2250 },
  { id: 1054, pt: "Lábios Fossilizados", en: "Ancient Lips", price: 500 },
  { id: 6144, pt: "Lágrimas de Arrependimento", en: "Regrettable Tears", price: 500 },
  { id: 7109, pt: "Lâmina de Lança Colossal", en: "Shining Spear Blade", price: 420 },
  { id: 7112, pt: "Lâmina de Papel", en: "Sharp Paper", price: 453 },
  { id: 7024, pt: "Lâmina Ensanguentada", en: "Bloody Edge", price: 5000 },
  { id: 7023, pt: "Lâmina Perdida nas Trevas", en: "Blade Lost in Darkness", price: 6000 },
  { id: 1015, pt: "Língua", en: "Tongue", price: 264 },
  { id: 903, pt: "Língua de Réptil", en: "Reptile Tongue", price: 70 },
  { id: 6095, pt: "Líquido Aromatizado", en: "Flavored Alcohol", price: 500 },
  { id: 7326, pt: "Líquido Fluorescente", en: "Fluorescent Liquid", price: 356 },
  { id: 6261, pt: "Macarrão Fino", en: "Fine Noodles", price: 250 },
  { id: 7068, pt: "Madeira Queimada", en: "Burnt Tree", price: 361 },
  { id: 11037, pt: "Mage Book Basic", en: "Mage Book Basic", price: 10 },
  { id: 11039, pt: "Mage Book Misc", en: "Mage Book Misc", price: 10 },
  { id: 11038, pt: "Mage Book Practice", en: "Mage Book Practice", price: 10 },
  { id: 7597, pt: "Magic Stone", en: "Magic Stone", price: 10 },
  { id: 6493, pt: "Makibishi", en: "Makibishi", price: 15 },
  { id: 7270, pt: "Mamadeira", en: "Nursing Bottle", price: 550 },
  { id: 1014, pt: "Mandíbula de Formiga", en: "Ant Jaw", price: 116 },
  { id: 958, pt: "Mandíbula Horrenda", en: "Horrendous Mouth", price: 195 },
  { id: 7165, pt: "Manto Cerimonial Celestial", en: "Transparent Celestial Robe", price: 325 },
  { id: 7127, pt: "Manual de Criação Vol.2: Álcool", en: "Alcohol Creation Guide", price: 50000 },
  { id: 7144, pt: "Manual de Criação: Vol.1: Poções Comuns", en: "Potion Creation Guide", price: 50000 },
  { id: 7128, pt: "Manual de Criação: Vol.3: Fogo Grego", en: "Bottle Grenade Creation Guide", price: 50000 },
  { id: 7129, pt: "Manual de Criação: Vol.4: Ácidos", en: "Acid Bottle Creation Guide", price: 50000 },
  { id: 7130, pt: "Manual de Criação: Vol.5: Plantas", en: "Plant Bottle Creation Guide", price: 50000 },
  { id: 7131, pt: "Manual de Criação: Vol.6: Explosivos", en: "Marine Sphere Creation Guide", price: 50000 },
  { id: 7132, pt: "Manual de Criação: Vol.7: Revestimentos", en: "Glistening Coat Creation Guide", price: 50000 },
  { id: 7133, pt: "Manual de Criação: Vol.8: Poções Compactas", en: "Condensed Potion Creation Guide", price: 120000 },
  { id: 7015, pt: "Marca-Página", en: "Bookclip in Memory", price: 1500 },
  { id: 1005, pt: "Martelo de Ferreiro", en: "Hammer of Blacksmith", price: 1 },
  { id: 7821, pt: "Maçã Bichada", en: "Green Apple", price: 10 },
  { id: 6254, pt: "Medalhões de Carne", en: "Beef Head", price: 50 },
  { id: 7034, pt: "Meia Furada", en: "Red Stocking", price: 50 },
  { id: 7219, pt: "Meia Listrada", en: "Striped Sock", price: 460 },
  { id: 6264, pt: "Melão", en: "Melon", price: 50 },
  { id: 708, pt: "Menta", en: "Ment", price: 250 },
  { id: 7583, pt: "Mente Maligna", en: "Evil Mind", price: 5 },
  { id: 11040, pt: "Mer Book Basic", en: "Mer Book Basic", price: 10 },
  { id: 11042, pt: "Mer Book Misc", en: "Mer Book Misc", price: 10 },
  { id: 11041, pt: "Mer Book Practice", en: "Mer Book Practice", price: 10 },
  { id: 11002, pt: "Mestre-Cuca Orleans Vol.1", en: "Chef King Orleans Vol.1", price: 4000 },
  { id: 757, pt: "Minério de Elunium", en: "Rough Elunium", price: 325 },
  { id: 1002, pt: "Minério de Ferro", en: "Iron Ore", price: 25 },
  { id: 7233, pt: "Minério de Mythril", en: "Mithril Ore", price: 10 },
  { id: 756, pt: "Minério de Oridecon", en: "Rough Oridecon", price: 275 },
  { id: 7231, pt: "Minério de Ouro", en: "Gold Ore", price: 10 },
  { id: 7232, pt: "Minério de Prata", en: "Silver Ore", price: 10 },
  { id: 7167, pt: "Misterioso Metal em Pano", en: "Strange Steel Piece", price: 215 },
  { id: 974, pt: "Mistura", en: "Mixture", price: 400 },
  { id: 6244, pt: "Mistura de Pólvora", en: "Gun Powder", price: 5 },
  { id: 734, pt: "Moldura Vermelha", en: "Red Frame", price: 1500 },
  { id: 7453, pt: "Molho Doce", en: "Sweet Sauce", price: 350 },
  { id: 6262, pt: "Molho Especial", en: "Cool Gravy", price: 200 },
  { id: 7455, pt: "Molho Picante", en: "Spicy Sauce", price: 350 },
  { id: 7454, pt: "Molho Saboroso", en: "Savory Sauce", price: 350 },
  { id: 7618, pt: "Monster Crystal", en: "Monster Crystal", price: 1 },
  { id: 7004, pt: "Monte de Lama", en: "Mud Lump", price: 438 },
  { id: 6106, pt: "Morango Maduro", en: "Well Ripened Berry", price: 10 },
  { id: 7292, pt: "Moscovita", en: "Muscovite", price: 1500 },
  { id: 938, pt: "Muco Pegajoso", en: "Sticky Mucus", price: 35 },
  { id: 6217, pt: "Muda de Mandrágora", en: "Mandragora Flowerpot", price: 1000 },
  { id: 7891, pt: "Mug", en: "Mug", price: 1 },
  { id: 6111, pt: "Mystic Stone", en: "Mystic Stone", price: 500 },
  { id: 7757, pt: "Mythril", en: "Mithril", price: 10 },
  { id: 7568, pt: "Máscara Branca", en: "White Mask", price: 530 },
  { id: 7114, pt: "Máscara do Faraó", en: "Masque of Tutankhamen", price: 5 },
  { id: 7187, pt: "Máscara do Festival", en: "Festival Mask", price: 50 },
  { id: 7157, pt: "Máscara Ninja", en: "Dark Mask", price: 157 },
  { id: 1045, pt: "Máscara Ritualística", en: "Cultish Masque", price: 206 },
  { id: 1009, pt: "Mão Divina", en: "Hand of God", price: 1 },
  { id: 951, pt: "Nadadeira", en: "Fin", price: 206 },
  { id: 7159, pt: "Nariz de Tengu", en: "Tengu Nose", price: 200 },
  { id: 997, pt: "Natureza Grandiosa", en: "Great Nature", price: 1500 },
  { id: 1051, pt: "Neurônio", en: "Detonator", price: 225 },
  { id: 11046, pt: "Ninja Book Basic", en: "Ninja Book Basic", price: 10 },
  { id: 11048, pt: "Ninja Book Misc", en: "Ninja Book Misc", price: 10 },
  { id: 11047, pt: "Ninja Book Practice", en: "Ninja Book Practice", price: 10 },
  { id: 7894, pt: "Nitrogen Acid", en: "Nitrogen Acid", price: 5 },
  { id: 7705, pt: "Nota do Geólogo", en: "Note of Geologist", price: 1 },
  { id: 1022, pt: "Nove-Caudas", en: "Nine Tails", price: 325 },
  { id: 7038, pt: "Novelo", en: "Yarn", price: 50 },
  { id: 7271, pt: "Novice Figure", en: "Novice Figure", price: 5000 },
  { id: 7314, pt: "O Sinal", en: "The Sign", price: 1 },
  { id: 7263, pt: "Olho de Gato", en: "Cat's Eye", price: 477 },
  { id: 7196, pt: "Ombreira", en: "Shoulder Protector", price: 115 },
  { id: 727, pt: "Opala", en: "Opal", price: 3000 },
  { id: 984, pt: "Oridecon", en: "Oridecon", price: 550 },
  { id: 7620, pt: "Oridecon Enriquecido", en: "Enriched Oridecon", price: 1 },
  { id: 6240, pt: "Oridecon Perfeito", en: "HD Oridecon", price: 10 },
  { id: 7435, pt: "Ornamento Dourado", en: "Golden Ornament", price: 953 },
  { id: 6105, pt: "Orvalho da Manhã", en: "Morning Dew", price: 10 },
  { id: 7141, pt: "Orvalho da Yggdrasil", en: "Morning Dew of Yggdrasil", price: 10000 },
  { id: 932, pt: "Osso", en: "Skel-Bone", price: 116 },
  { id: 969, pt: "Ouro", en: "Gold", price: 100000 },
  { id: 7228, pt: "Ouro em Barra", en: "Gold Bullion", price: 50000 },
  { id: 7863, pt: "Ouro Especial", en: "Special Gold", price: 10 },
  { id: 908, pt: "Ova de Sapo", en: "Spawn", price: 70 },
  { id: 7197, pt: "Palha", en: "Tough Vines", price: 250 },
  { id: 7035, pt: "Palito de Fósforo", en: "Matchstick", price: 50 },
  { id: 7742, pt: "Palmito em Conserva", en: "Kaong", price: 1 },
  { id: 7482, pt: "Panela", en: "Pot", price: 100 },
  { id: 7151, pt: "Papel Amarelado", en: "Oil Paper", price: 105 },
  { id: 7317, pt: "Parafuso Enferrujado", en: "Rusty Screw", price: 267 },
  { id: 7938, pt: "Partículas de Luz", en: "Light Granule", price: 500 },
  { id: 7350, pt: "Passe", en: "Pass", price: 10 },
  { id: 7342, pt: "Pasta de Arquivos", en: "File Folder", price: 10 },
  { id: 7343, pt: "Pasta de Arquivos Selada", en: "Sealed File Folder", price: 10 },
  { id: 7202, pt: "Pata de Besouro", en: "Pincher of Beetle", price: 145 },
  { id: 1042, pt: "Pata de Inseto", en: "Bug Leg", price: 215 },
  { id: 1030, pt: "Pata de Tigre", en: "Tiger's Footskin", price: 750 },
  { id: 948, pt: "Pata de Urso", en: "Bear's Footskin", price: 87 },
  { id: 918, pt: "Pata Pegajosa", en: "Sticky Webfoot", price: 10 },
  { id: 7150, pt: "Pedaço de Bambu", en: "Piece of Bamboo", price: 155 },
  { id: 7032, pt: "Pedaço de Casca de Ovo", en: "Piece of Egg Shell", price: 84 },
  { id: 7356, pt: "Pedaço de Crista", en: "Crest Piece", price: 2500 },
  { id: 7357, pt: "Pedaço de Crista", en: "Crest Piece", price: 2500 },
  { id: 7358, pt: "Pedaço de Crista", en: "Crest Piece", price: 2500 },
  { id: 7359, pt: "Pedaço de Crista", en: "Crest Piece", price: 2500 },
  { id: 7703, pt: "Pedaço de Engrenagem", en: "Piece of Cogwheel", price: 1 },
  { id: 7012, pt: "Pedaço de Escama Dura", en: "Tough Scalelike Stem", price: 206 },
  { id: 7108, pt: "Pedaço de Escudo Colossal", en: "Piece of Shield", price: 840 },
  { id: 7507, pt: "Pedaço de Ferro Sólido", en: "Solid Iron Piece", price: 421 },
  { id: 7974, pt: "Pedaço de Ilusão", en: "Illusion Piece", price: 10 },
  { id: 7095, pt: "Pedaço de Metal", en: "Metal Fragment", price: 537 },
  { id: 7111, pt: "Pedaço de Papel", en: "Slick Paper", price: 353 },
  { id: 7067, pt: "Pedaço de Pedra", en: "Stone Fragment", price: 320 },
  { id: 7346, pt: "Pedaço do Coração de Ymir", en: "Ymir's Heart Piece", price: 10 },
  { id: 6320, pt: "Pedra das Valquírias", en: "Premium Reset Stone", price: 10 },
  { id: 7521, pt: "Pedra do Fogo", en: "Flame Stone", price: 75 },
  { id: 7522, pt: "Pedra do Gelo", en: "Ice Stone", price: 75 },
  { id: 7825, pt: "Pedra do Herói", en: "Heroic Stone", price: 10 },
  { id: 7102, pt: "Pedra do Pesadelo", en: "Nightmare", price: 537 },
  { id: 7523, pt: "Pedra do Vento", en: "Wind Stone", price: 75 },
  { id: 7096, pt: "Pedra Pome", en: "Lava", price: 554 },
  { id: 7300, pt: "Pedras Preciosas", en: "Gemstone", price: 710 },
  { id: 6096, pt: "Peixe Azulado", en: "Fish With Blue Back", price: 10 },
  { id: 7003, pt: "Pele de Anolian", en: "Anolian Skin", price: 484 },
  { id: 7107, pt: "Pele de Bode", en: "Antelope Skin", price: 378 },
  { id: 7123, pt: "Pele de Dragão", en: "Dragon Skin", price: 512 },
  { id: 7171, pt: "Pele de Leopardo", en: "Leopard Skin", price: 141 },
  { id: 7065, pt: "Pele de Lontra", en: "Sea-Otter Fur", price: 410 },
  { id: 1055, pt: "Pele de Minhoca", en: "Earthworm Peeling", price: 98 },
  { id: 7155, pt: "Pele de Sapo", en: "Poisonous Toad Skin", price: 140 },
  { id: 1029, pt: "Pele de Tigre", en: "Tiger Skin", price: 274 },
  { id: 955, pt: "Pele de Verme", en: "Worm Peeling", price: 26 },
  { id: 6022, pt: "Pele Dura", en: "Hard Skin", price: 442 },
  { id: 7161, pt: "Pele Negra de Urso", en: "Black Bear Skin", price: 192 },
  { id: 7122, pt: "Pelugem Incandescente", en: "Burning Hair", price: 487 },
  { id: 7441, pt: "Pena Azul", en: "Blue Feather", price: 704 },
  { id: 7101, pt: "Pena de Grand Peco", en: "Peco Peco Feather", price: 227 },
  { id: 7115, pt: "Pena de Harpia", en: "Harpy Feather", price: 571 },
  { id: 7063, pt: "Pena Macia", en: "Soft Feather", price: 140 },
  { id: 7440, pt: "Pena Vermelha", en: "Red Feather", price: 667 },
  { id: 1039, pt: "Pequena Asa Maligna", en: "Little Evil Wing", price: 1000 },
  { id: 7268, pt: "Pequena Boneca Fantasma", en: "Little Ghost Doll", price: 605 },
  { id: 1038, pt: "Pequeno Chifre Maligno", en: "Little Evil Horn", price: 264 },
  { id: 725, pt: "Peridoto", en: "Sardonyx", price: 3000 },
  { id: 940, pt: "Perna de Gafanhoto", en: "Grasshopper's Leg", price: 18 },
  { id: 7316, pt: "Perna de Inseto", en: "Insect Leg", price: 329 },
  { id: 7020, pt: "Pesadelo Maternal", en: "Mother's Nightmare", price: 10 },
  { id: 7450, pt: "Peça de Armadura de Esqueleto", en: "Skeletal Armor Piece", price: 1025 },
  { id: 7512, pt: "Peça Queimada", en: "Burnt Part", price: 800 },
  { id: 7762, pt: "Pilão Yaga", en: "Yaga's Pestle", price: 10 },
  { id: 7286, pt: "Pimenta Vermelha", en: "Red Chile", price: 10 },
  { id: 6122, pt: "Pincel de Grafite", en: "Paint Brush", price: 5 },
  { id: 6121, pt: "Pincel de Maquiagem", en: "Makeover Brush", price: 5 },
  { id: 7125, pt: "Pinças de Escorpião", en: "Scorpion Claw", price: 353 },
  { id: 7875, pt: "Pirate Treasure", en: "Pirate Treasure", price: 150000 },
  { id: 7296, pt: "Piroxênio", en: "Pyroxene", price: 1500 },
  { id: 7319, pt: "Placa de Ferro Usada", en: "Used Iron Plate", price: 512 },
  { id: 6109, pt: "Plant Neutrient", en: "Plant Neutrient", price: 10 },
  { id: 707, pt: "Planta da Melodia", en: "Singing Plant", price: 250 },
  { id: 7230, pt: "Platina em Barra", en: "Platinum Bullion", price: 100000 },
  { id: 949, pt: "Pluma", en: "Feather", price: 10 },
  { id: 916, pt: "Plumas de Ave", en: "Feather of Birds", price: 5 },
  { id: 1001, pt: "Poeira Estelar", en: "Star Dust", price: 750 },
  { id: 7320, pt: "Poeira Poluente", en: "Dust Pollutant", price: 128 },
  { id: 7154, pt: "Poeira Venenosa", en: "Poisonous Powder", price: 80 },
  { id: 1095, pt: "Ponteiro", en: "Needle of Alarm", price: 273 },
  { id: 7121, pt: "Pote de Mel", en: "Honey Pot", price: 311 },
  { id: 7229, pt: "Prata em Barra", en: "Silver Bullion", price: 25000 },
  { id: 7149, pt: "Prato Amarelado", en: "Yellow Plate", price: 110 },
  { id: 736, pt: "Prato de Porcelana", en: "China", price: 500 },
  { id: 7352, pt: "Prato Transparente", en: "Transparent Plate", price: 10 },
  { id: 7353, pt: "Prato Transparente", en: "Transparent Plate", price: 10 },
  { id: 7354, pt: "Prato Transparente", en: "Transparent Plate", price: 10 },
  { id: 7355, pt: "Prato Transparente", en: "Transparent Plate", price: 10 },
  { id: 1063, pt: "Presa", en: "Fang", price: 340 },
  { id: 7036, pt: "Presa de Hati", en: "Fang of Hatii", price: 50 },
  { id: 922, pt: "Presa de Orc", en: "Orc's Fang", price: 110 },
  { id: 1044, pt: "Presa de Zenorc", en: "Zenorc's Fang", price: 132 },
  { id: 7744, pt: "Pudim de Leite", en: "Leche Flan", price: 1 },
  { id: 1097, pt: "Página Deteriorada", en: "Worn Out Page", price: 474 },
  { id: 7449, pt: "Página Sangrenta", en: "Bloody Page", price: 340 },
  { id: 722, pt: "Pérola", en: "Pearl", price: 3000 },
  { id: 6020, pt: "Pêlo", en: "Fur", price: 352 },
  { id: 7164, pt: "Pêssego Petrificado", en: "Solid Peach", price: 200 },
  { id: 7226, pt: "Pílula", en: "Pellet", price: 1 },
  { id: 6246, pt: "Pó Amarelo", en: "Yellow Powder", price: 50 },
  { id: 6247, pt: "Pó Branco", en: "White Powder", price: 50 },
  { id: 7001, pt: "Pó de Bolor", en: "Mould Powder", price: 233 },
  { id: 924, pt: "Pó de Borboleta", en: "Powder of Butterfly", price: 45 },
  { id: 1057, pt: "Pó de Traça", en: "Moth Dust", price: 69 },
  { id: 6213, pt: "Pó Explosivo", en: "Explosive Powder", price: 250 },
  { id: 6245, pt: "Pó Negro", en: "Black Powder", price: 50 },
  { id: 7204, pt: "Pólvora", en: "Gunpowder", price: 160 },
  { id: 7293, pt: "Quartzo Rosa", en: "Rose Quartz", price: 1500 },
  { id: 6326, pt: "Queen Wing Piece", en: "Queen Wing Piece", price: 815 },
  { id: 11056, pt: "Quia do Espiritualista", en: "Elemental Spirit Guide", price: 500 },
  { id: 6260, pt: "Rabo de Petite", en: "Petite's Tail", price: 50 },
  { id: 1033, pt: "Raiz de Planta Carnívora", en: "Maneater Root", price: 104 },
  { id: 902, pt: "Raiz de Árvore", en: "Tree Root", price: 6 },
  { id: 7188, pt: "Raiz Marrom", en: "Brown Root", price: 280 },
  { id: 6321, pt: "Rakehorn Helm", en: "Rakehorn Helm", price: 411 },
  { id: 6256, pt: "Raspadinha", en: "Ice Piece", price: 50 },
  { id: 7824, pt: "Refresco", en: "Spirit Liquor", price: 10 },
  { id: 7513, pt: "Relógio de Bolso", en: "Pocket Watch", price: 1710 },
  { id: 7765, pt: "Remédio de Baba-Yaga", en: "Baba Yaga's Secret Medicine", price: 10 },
  { id: 7402, pt: "Republik", en: "Republik", price: 1 },
  { id: 907, pt: "Resina", en: "Resin", price: 60 },
  { id: 7205, pt: "Retalho Negro", en: "Piece of Black Cloth", price: 263 },
  { id: 7869, pt: "Rice Pouch", en: "Rice Pouch", price: 5 },
  { id: 7729, pt: "Rok Star Badge", en: "Rok Star Badge", price: 10 },
  { id: 7905, pt: "Rok Star Badge", en: "Rok Star Badge", price: 10 },
  { id: 749, pt: "Rosa de Gelo", en: "Frozen Rose", price: 17500 },
  { id: 748, pt: "Rosa Eterna", en: "Witherless Rose", price: 27500 },
  { id: 6393, pt: "Round Feather", en: "Round Feather", price: 350 },
  { id: 723, pt: "Rubi", en: "Ruby", price: 3000 },
  { id: 724, pt: "Rubi Amaldiçoado", en: "Cursed Ruby", price: 300 },
  { id: 7273, pt: "RWC Necklace", en: "RWC Necklace", price: 1 },
  { id: 7922, pt: "RWC Voucher Items", en: "RWC Voucher Items", price: 1 },
  { id: 1064, pt: "Rédeas", en: "Reins", price: 401 },
  { id: 7635, pt: "Sachet", en: "Sachet", price: 50 },
  { id: 726, pt: "Safira", en: "Sapphire", price: 3000 },
  { id: 1049, pt: "Saia Virginal", en: "Skirt of Virgin", price: 850 },
  { id: 6389, pt: "Sample Of Puddle Research", en: "Sample Of Puddle Research", price: 10 },
  { id: 702, pt: "Sangue de Animal", en: "Animal Gore", price: 225 },
  { id: 6252, pt: "Sangue de Lobo", en: "Blood Of Wolf", price: 50 },
  { id: 990, pt: "Sangue Escarlate", en: "Red Blood", price: 500 },
  { id: 6388, pt: "Scale Sample", en: "Scale Sample", price: 10 },
  { id: 911, pt: "Scell", en: "Scell", price: 80 },
  { id: 7949, pt: "Seda de Felpa", en: "Woven Wool", price: 5 },
  { id: 7166, pt: "Seda Macia", en: "Soft Silk", price: 600 },
  { id: 7399, pt: "Selamat", en: "Selamat", price: 1 },
  { id: 7193, pt: "Semente", en: "Sprout", price: 115 },
  { id: 7140, pt: "Semente da Vida", en: "Seed of Life", price: 30000 },
  { id: 6211, pt: "Semente de Planta Sanguessuga", en: "Bloodsuck Plant Seed", price: 400 },
  { id: 6210, pt: "Semente de Planta Selvagem", en: "Seed Of Thorny Plant", price: 300 },
  { id: 7156, pt: "Shuriken Despedaçado", en: "Broken Shuriken", price: 235 },
  { id: 7579, pt: "Silk Handkerchief of Zhi Nu", en: "Silk Handkerchief of Zhi Nu", price: 10 },
  { id: 6324, pt: "Single Horned Helmet", en: "Single Horned Helmet", price: 351 },
  { id: 6319, pt: "Small Bradium", en: "Small Bradium", price: 162 },
  { id: 6390, pt: "Small Pocket", en: "Small Pocket", price: 10 },
  { id: 7170, pt: "Smoking", en: "Tuxedo", price: 21500 },
  { id: 11052, pt: "SN Book Basic", en: "SN Book Basic", price: 10 },
  { id: 11054, pt: "SN Book Misc", en: "SN Book Misc", price: 10 },
  { id: 11053, pt: "SN Book Practice", en: "SN Book Practice", price: 10 },
  { id: 7594, pt: "Sonia's Letter", en: "Sonia's Letter", price: 10 },
  { id: 7702, pt: "Special Cogwheel", en: "Special Cogwheel", price: 1 },
  { id: 7596, pt: "Special Shield", en: "Special Shield", price: 10 },
  { id: 7595, pt: "Special Sword", en: "Special Sword", price: 10 },
  { id: 6391, pt: "Splendid Supply Kit", en: "Splendid Supply Kit", price: 10 },
  { id: 7758, pt: "Star Crystal", en: "Star Crystal", price: 10 },
  { id: 7893, pt: "Sulphur", en: "Sulphur", price: 5 },
  { id: 7415, pt: "Summoning Stone", en: "Summoning Stone", price: 1 },
  { id: 7019, pt: "Sussurros de Loki", en: "Loki's Whispers", price: 10 },
  { id: 11025, pt: "Swordman Book Basic", en: "Swordman Book Basic", price: 10 },
  { id: 11026, pt: "Swordman Book Practice", en: "Swordman Book Practice", price: 10 },
  { id: 11027, pt: "Swrodman Book Misc", en: "Swrodman Book Misc", price: 10 },
  { id: 7611, pt: "Symbol of Fox", en: "Symbol of Fox", price: 10 },
  { id: 7347, pt: "Tabela de Pesquisa", en: "Research Chart", price: 420 },
  { id: 7267, pt: "Tanga de Tigre", en: "Tiger Panty", price: 149 },
  { id: 7050, pt: "Tapete de Algodão", en: "Cotton Mat", price: 50 },
  { id: 7051, pt: "Tapete de Seda", en: "Silk Mat", price: 50 },
  { id: 1059, pt: "Tecido", en: "Fabric", price: 153 },
  { id: 6299, pt: "Tecido Velho", en: "Worn Cloth Piece", price: 10 },
  { id: 6387, pt: "Teeth Sample", en: "Teeth Sample", price: 10 },
  { id: 1025, pt: "Teia de Aranha", en: "Cobweb", price: 92 },
  { id: 1050, pt: "Tendões", en: "Tendon", price: 110 },
  { id: 962, pt: "Tentáculo", en: "Tentacle", price: 35 },
  { id: 6259, pt: "Tentáculo de Drosera", en: "Drosera Tentacle", price: 50 },
  { id: 7704, pt: "Termômetro Quebrado", en: "Broken Thermometer", price: 1 },
  { id: 11028, pt: "Thief Book Basic", en: "Thief Book Basic", price: 10 },
  { id: 11030, pt: "Thief Book Misc", en: "Thief Book Misc", price: 10 },
  { id: 11029, pt: "Thief Book Practice", en: "Thief Book Practice", price: 10 },
  { id: 1024, pt: "Tinta de Polvo", en: "Squid Ink", price: 132 },
  { id: 6123, pt: "Tinta para Parede", en: "Surface Paint", price: 100 },
  { id: 6120, pt: "Tinta para Pele", en: "Face Paint", price: 60 },
  { id: 976, pt: "Tintura Amarela", en: "Lemon Dyestuffs", price: 4000 },
  { id: 978, pt: "Tintura Azul", en: "Cobaltblue Dyestuffs", price: 4000 },
  { id: 982, pt: "Tintura Branca", en: "White Dyestuffs", price: 4000 },
  { id: 980, pt: "Tintura Laranja", en: "Orange Dyestuffs", price: 4000 },
  { id: 983, pt: "Tintura Preta", en: "Black Dyestuffs", price: 4000 },
  { id: 979, pt: "Tintura Verde", en: "Darkgreen Dyestuffs", price: 4000 },
  { id: 975, pt: "Tintura Vermelha", en: "Scarlet Dyestuffs", price: 4000 },
  { id: 981, pt: "Tintura Violeta", en: "Violet Dyestuffs", price: 4000 },
  { id: 11043, pt: "TK Book Basic", en: "TK Book Basic", price: 10 },
  { id: 11045, pt: "TK Book Misc", en: "TK Book Misc", price: 10 },
  { id: 11044, pt: "TK Book Practice", en: "TK Book Practice", price: 10 },
  { id: 7021, pt: "Tolice do Cego", en: "Foolishness of the Blind", price: 10 },
  { id: 728, pt: "Topázio", en: "Topaz", price: 3000 },
  { id: 7201, pt: "Tora", en: "Log", price: 125 },
  { id: 1056, pt: "Torrão de Areia", en: "Grit", price: 153 },
  { id: 7041, pt: "Torrão de Areia Fina", en: "Fine Grit", price: 60 },
  { id: 6097, pt: "Torta Assustadora", en: "Pumpkin Pie", price: 10 },
  { id: 6094, pt: "Traditional Sweets", en: "Traditional Sweets", price: 10 },
  { id: 6296, pt: "Training Notice", en: "Training Notice", price: 10 },
  { id: 901, pt: "Trança", en: "Daenggie", price: 130 },
  { id: 1094, pt: "Trança Curta", en: "Short Daenggie", price: 139 },
  { id: 6041, pt: "Trepadeira Resistente", en: "Strong Vine", price: 15 },
  { id: 705, pt: "Trevo", en: "Clover", price: 5 },
  { id: 706, pt: "Trevo de Quatro Folhas", en: "Four Leaf Clover", price: 40000 },
  { id: 1019, pt: "Tronco", en: "Trunk", price: 30 },
  { id: 1066, pt: "Tronco de Alta Qualidade", en: "Fine-grained Trunk", price: 1 },
  { id: 7850, pt: "Tronco Especial", en: "Wooden Block", price: 10 },
  { id: 1068, pt: "Tronco Estéril", en: "Barren Trunk", price: 1 },
  { id: 1067, pt: "Tronco Sólido", en: "Solid Trunk", price: 1 },
  { id: 1092, pt: "Tubo de Ensaio", en: "Empty Test Tube", price: 1 },
  { id: 7325, pt: "Tubo Flexível", en: "Flexible Tube", price: 51 },
  { id: 7294, pt: "Turquesa", en: "Turquoise", price: 1500 },
  { id: 6323, pt: "Two-Horned Helmet", en: "Two-Horned Helmet", price: 364 },
  { id: 957, pt: "Unha Apodrecida", en: "Decayed Nail", price: 41 },
  { id: 1099, pt: "Uniforme Velho de Presidiário", en: "Worn-out Prison Uniform", price: 340 },
  { id: 6382, pt: "Urn", en: "Urn", price: 10 },
  { id: 7753, pt: "Utensílio Rural Quebrado", en: "Broken Farming Utensil", price: 165 },
  { id: 7134, pt: "Vasilha de Mistura", en: "Medicine Bowl", price: 4 },
  { id: 6255, pt: "Vasilha Grande", en: "Large Cookpot", price: 250 },
  { id: 6248, pt: "Vasilha Melange", en: "Melange Pot", price: 300 },
  { id: 7117, pt: "Velho Grimório", en: "Torn Magic Book", price: 571 },
  { id: 7153, pt: "Velho Obi", en: "Worn-out Kimono", price: 295 },
  { id: 7565, pt: "Veneno Pegajoso", en: "Sticky Poison", price: 175 },
  { id: 996, pt: "Vento Bruto", en: "Rough Wind", price: 1500 },
  { id: 993, pt: "Vida Verdejante", en: "Green Live", price: 500 },
  { id: 7279, pt: "Vita500 Lid", en: "Vita500 Lid", price: 5 },
  { id: 7966, pt: "Weird Parchment1", en: "Weird Parchment1", price: 5 },
  { id: 7967, pt: "Weird Parchment2", en: "Weird Parchment2", price: 5 },
  { id: 7968, pt: "Weird Parchment3", en: "Weird Parchment3", price: 5 },
  { id: 7969, pt: "Weird Parchment4", en: "Weird Parchment4", price: 5 },
  { id: 6325, pt: "White Spider Limb", en: "White Spider Limb", price: 502 },
  { id: 6514, pt: "Wind Amulet", en: "Wind Amulet", price: 50 },
  { id: 7614, pt: "Wrapping Paper", en: "Wrapping Paper", price: 5 },
  { id: 7406, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7407, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7408, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7409, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7410, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7411, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7412, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7413, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 7414, pt: "Yuebing", en: "Yuebing", price: 1 },
  { id: 912, pt: "Zargônio", en: "Zargon", price: 240 },
  { id: 729, pt: "Zircônio", en: "Zircon", price: 3000 },
  { id: 1062, pt: "Zé-Lanterna", en: "Jack o' Pumpkin", price: 187 },
  { id: 7291, pt: "Ágata", en: "Agate", price: 1500 },
  { id: 7795, pt: "Álbum de Fotos de Mammi", en: "Mammi's Photo Album", price: 1 },
  { id: 970, pt: "Álcool", en: "Alcohol", price: 200 },
  { id: 7457, pt: "Óleo de Cozinha", en: "Cooking Oil", price: 250 },
];
